# Site settings
title: Computational Neuroscience at NMBU
description: > # this means to ignore newlines until "baseurl:"
  Computational Neuroscience Group at the Norwegian University of Life Sciences

# Build settings
markdown: redcarpet
highlighter: pygments
